#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo "GIT pre-push : Running Jasmine unit tests..."
output=$(node_modules/.bin/babel-node node_modules/.bin/jasmine --config=jasmine.json)

if [[ $? != 0 ]]; then
    echo "$output"
    printf "\n${RED}GIT PUSH ABORTED - jasmine test(s) failed ${NC}\n\n"
    exit 1
fi

echo "$output"
printf "\n${GREEN}Pre-push unit test run passed, allow git push ${NC}\n\n"

exit 0
